[package]
name = "wetutil"
description = "One-stop crate for all the rust features that I'm missing"
version = "0.5.0"
edition = "2021"

license = "MIT"
homepage = "https://github.com/wetfloo/wetutil"
repository = "https://github.com/wetfloo/wetutil"
rust-version = "1.76"

[dependencies]
pretty-type-name-alloc = { version = "1", optional = true }

[features]
default = ["type-name"]

type-name = ["alloc", "dep:pretty-type-name-alloc"]

alloc = []
std = ["alloc"]
